### PR TITLE
Make GSAnchor creation compatible with both Glyphs 3 and 4

### PR DESCRIPTION
**Pull request by mekkablue**
## Problem

Commit 5ec06ad replaced `GSAnchor(name, position)` with `GSAnchor.alloc().initWithName_position_(name, position)` to work around Glyphs 4 rejecting positional arguments. That initializer does not exist in Glyphs 3, so the affected scripts now fail there:

```
Quote Manager Error: 'GSAnchor' object has no attribute 'initWithName_position_'
  File "Quote Manager.py", line 349, in setAnchors
    layer.anchors.append(GSAnchor.alloc().initWithName_position_("#entry", NSPoint(0, 0)))
AttributeError: 'GSAnchor' object has no attribute 'initWithName_position_'
```

## Changes

- `__init__.py`: new shared helper `newAnchorWithName(anchorName, position=None)` that branches on `Glyphs.versionNumber` — the ObjC initializer for Glyphs 4 and up, positional arguments for Glyphs 3 and earlier. Placed next to the existing `newGlyphWithName()` / `newLineControlLayer()` workarounds.
- All 14 call sites introduced by 5ec06ad now go through the helper, across 8 scripts:
  - `Anchors/Add ZWRO origin Anchors.py`
  - `Anchors/Add missing smart anchors.py`
  - `Anchors/Exit-Entry Manager.py`
  - `Anchors/Fix Arabic Anchor Order in Ligatures.py`
  - `Anchors/Steal Anchors.py`
  - `Build Glyphs/Build Q from O and _tail.Q.py`
  - `Build Glyphs/Quote Manager.py`
  - `Paths/Rotate around anchor.py`
- Imports adjusted: `newAnchorWithName` imported from `mekkablue`, `GSAnchor` dropped from `GlyphsApp` imports where it is no longer referenced (it stays where bare `GSAnchor()` is still used).
- `CLAUDE.md`: helper documented in the shared-utilities table.

Bare `GSAnchor()` calls with no arguments were already version-safe and are left untouched.

## Verification

All touched files compile (`py_compile`), and `flake8` reports the same 25 pre-existing findings as on `master` — no new ones.

---
_Generated by [Claude Code](https://claude.ai/code/session_01H1e8GzNxNqd4qufSyHTjRn)_

### CODE REVIEW

**Comment by schriftgestalt** [comment]
> to work around Glyphs 4 rejecting positional arguments

That's fixed. And both changes (this one and 5ec06ad) should come out again. And it was also only a problem in very specific conditions . So for most people it always worked with `GSAnchor()`.
