### ISSUE TITLE
Components/Sync Components Across Masters.py doesn't work anymore

### ISSUE THREAD

**Issue by justinpenner** [mekkablue/Glyphs-Scripts#328]
I suspect this is due to it referring to a future property of GSGlyph that will be coming in 3.2.

```
🔠 Syncing components in A...

⚠️ Script Error:

Traceback (most recent call last):
  File "Sync Components Across Masters.py", line 89
    process(thisLayer)
  File "Sync Components Across Masters.py", line 33, in process
    for layerGroup in thisGlyph.layerGroups():
AttributeError: 'NSKVONotifying_GSGlyph' object has no attribute 'layerGroups'


Traceback (most recent call last):
  File "Sync Components Across Masters.py", line 98
    raise e
  File "Sync Components Across Masters.py", line 89
    process(thisLayer)
  File "Sync Components Across Masters.py", line 33, in process
    for layerGroup in thisGlyph.layerGroups():
AttributeError: 'NSKVONotifying_GSGlyph' object has no attribute 'layerGroups'
```

ETA: It looks like the breaking change was probably in e25f81a

**Comment by schriftgestalt** [comment]
fixed.
