### ISSUE TITLE
Alignment manager not working in GlyphsApp 3.2

### ISSUE THREAD

**Issue by RosaWagner** [mekkablue/Glyphs-Scripts#293]
```
Traceback (most recent call last):
  File "Alignment Manager.py", line 8
    import vanilla
  File "__init__.py", line 6
    from vanilla.vanillaColorWell import ColorWell
  File "vanillaColorWell.py", line 5
    from AppKit import NSColorWellStyleDefault, NSColorWellStyleMinimal, NSColorWellStyleExpanded
ImportError: cannot import name 'NSColorWellStyleDefault' from 'AppKit._AppKit' (/Users/rosalie/Library/Application Support/Glyphs 3/Repositories/GlyphsPythonPlugin/Python.framework/Versions/3.9/lib/python3.9/site-packages/AppKit/_AppKit.cpython-39-darwin.so)
```

**Comment by schriftgestalt** [comment]
The version of vanilla and python (pyobjc) that you are using are not compatible. Either you install a current version of python (e.g. using the installer from [python.org](http://python.org/)). Or use the vanilla version from the plugin manager.
