### ISSUE TITLE
'Convert RTL Kerning from Glyphs 2 to 3' script compatibility with Glyphs version >= 3.2.3

### ISSUE THREAD

**Issue by jackmcDaMa** [mekkablue/Glyphs-Scripts#346]
This script does not seem to work in Glyphs version 3.2.3. I can confirm it does work fine in version 3.1.2

Error produced:

 `AttributeError: 'GSExportInstanceOperation' object has no attribute '_makeCachesKey2Scripts_splitGroups_groupDict_glyphsID2Glyph_name2Glyph_error_'`

The referenced code:
https://github.com/mekkablue/Glyphs-Scripts/blob/c69821b17a5f9a7151630fdf9cfb5303ebd0b2ba/Kerning/Convert%20RTL%20Kerning%20from%20Glyphs%202%20to%203.py#L154-L157

Sounds like maybe this needs to be updated in order to be compatible with the latest versions on Glyphs.app, although it is not clear to me exactly what this change would look like.
